apiVersion: v1
kind: BuildConfig
metadata:
  name: s2i-openjdk
  labels:
    app: s2i-openjdk
spec:
  triggers: {}
  source:
    type: Git
    git:
      ref: master
      uri: https://github.com/iptrha/openshift_techbier
    contextDir: 2_s2i-openjdk_setup/docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: s2i-openjdk:latest
  resources: {}
