kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "helloworld-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/iptrha/openshift_techbier.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: 4_helloworld/openshift/pipeline.yml
      env:
        - name: GIT_URL
          value: "https://github.com/iptrha/openshift_techbier.git"
        - name: GIT_BRANCH
          value: "master"
