stage ( "build" )
{
  node ()
  {
    git branch: params.GIT_BRANCH, url: GIT_URL
    sh "oc apply -f 4_helloworld/openshift/buildconfig.yml"

    sh "start-build helloworld"
  }
}

stage ( "deploy to devl" )
{


  sh "oc "

}

stage ( "deploy to test" )
{

}

stage ( "manual quality gate" )
{

}

stage ( "deploy to prod" )
{

}
